"""add_recurring_patterns

Revision ID: 4d646e3dc8e8
Revises: 7f416ec41972
Create Date: 2026-06-21 09:11:30.515478

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4d646e3dc8e8'
down_revision: Union[str, None] = '7f416ec41972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=False),
    sa.Column('avg_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('last_flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'merchant', name='uq_recurring_user_cat_merchant')
    )
    op.create_index(op.f('ix_recurring_patterns_id'), 'recurring_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_patterns_user_id'), 'recurring_patterns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_patterns_user_id'), table_name='recurring_patterns')
    op.drop_index(op.f('ix_recurring_patterns_id'), table_name='recurring_patterns')
    op.drop_table('recurring_patterns')
    # ### end Alembic commands ###
