"""budget_period_redesign

Revision ID: 7e524ccefe24
Revises: e1e0768c8bc8
Create Date: 2026-06-20 16:22:40.627510

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7e524ccefe24'
down_revision: Union[str, None] = 'e1e0768c8bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns; period gets a server default so existing rows aren't rejected,
    # then we backfill period_start from the old month/year columns before dropping them.
    op.add_column('budgets', sa.Column('period', sa.String(length=20),
                                       nullable=False, server_default='monthly'))
    op.add_column('budgets', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('budgets', sa.Column('period_end', sa.Date(), nullable=True))

    # Backfill: set period_start = first day of the old period_month/period_year
    op.execute(
        "UPDATE budgets SET period_start = make_date(period_year, period_month, 1)"
    )

    op.drop_column('budgets', 'period_year')
    op.drop_column('budgets', 'period_month')

    # Remove the server_default — app layer controls this going forward
    op.alter_column('budgets', 'period', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('period_month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('budgets', 'period_end')
    op.drop_column('budgets', 'period_start')
    op.drop_column('budgets', 'period')
    # ### end Alembic commands ###
