"""audit_log_reallocation_fields

Revision ID: 7f416ec41972
Revises: 7e524ccefe24
Create Date: 2026-06-21 09:01:16.934727

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7f416ec41972'
down_revision: Union[str, None] = '7e524ccefe24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('proposal_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('audit_logs', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_audit_logs_proposal_id'), 'audit_logs', ['proposal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_proposal_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'undone_at')
    op.drop_column('audit_logs', 'executed_at')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'proposal_id')
    # ### end Alembic commands ###
